commoninfra:
  slack_channel: '#onepilot-cloud-alerts'
  keyvaultName: "SHOULD_BE_OVERRIDDEN_IN_DEPLOYMENT"
  secretProviderIdentityId: "SHOULD_BE_OVERRIDDEN_IN_DEPLOYMENT"
  tenantId: "2add9d3d-b354-49e2-a68d-ee84001ffd34"
  cloudName: azurecloud